sudo: false
language: python
addons:
  apt:
    packages:
      - libenchant-dev
env:
    - TOX_ENV=py27-django111
install:
  - pip install tox gu-django-filebrowser-no-grappelli
script:
  - tox -e $TOX_ENV
after_success:
  - pip install coveralls
  - coveralls
